services:
 api:
  image: node:latest
  volumes:
    - ./api_src:/root/nodeapp
    - ./dev.sh:/root/dev.sh
  ports:
    - 3000:3000
  
  entrypoint: ["/bin/bash","/root/dev.sh"]
  command: ["nodemon", "/root/nodeapp"]
  tty: true
  stdin_open: true
  