services:
 api:
  image: node:latest
  volumes:
    - ./api_src:/root/nodeapp
    - ./dev.sh:/root/dev.sh
  ports:
    - 3000:3000

  entrypoint: ["/bin/bash","/root/dev.sh"]
  command: ["nodemon", "/root/nodeapp"]
  tty: true
  stdin_open: true

 mysql:
  image: mysql:oraclelinux9
  ports:
   - 3306:3306
  volumes:
    - ./mysql-init:/docker-entrypoint-initdb.d
  environment: 
   MYSQL_ROOT_PASSWORD: 'test123!'